sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
  - '6'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - export NPM_TAG=([ "$TRAVIS_BRANCH" == "master" ] && echo "latest" || echo $TRAVIS_BRANCH)
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
